### PR TITLE
Add option to change keybind, Add slider for speed, Add play/pause button, fix for #9 and linux in general, refactor, add timer with pause option, option to hide screen on open (useful for starting on boot), check if instance is running already and open menu if so

### PR DESCRIPTION
**Pull request by danimateo**
- **Keybind change**: User can change the keybind by typing it on the keyboard after pressing the button. One issue is that it doesn't show Cmd for OSX in the helper, we need one more check for that using the platform from env
 - **Fix for tiling WM** (#9), focusable tag on the browser window decouples the window from the WM, setting the required X11 props
 - **Refactor** - remove unnecessary async / await  in some methods, add return types to computed (this can cause issues with typescript in Vue), some other little tweaks

### CODE REVIEW

**Comment by danimateo** [comment]
So, in Linux the best option is to set focusable false for the browser window, that prevents the hack with the `setInterval()` and also covers the whole screen on all window managers. The only problem is that you can't use your keyboard if it's not focusable, so keybind changing from the main window is not possible. 

I have created a separated dialog that takes the keybind and sets it (opened from the main window ofc), but it doesn't appear in front of the other window (only on Linux, seems like it's not possible. `{focusable: false}` has the highest priority.)

I have also made some refactoring and styling changes (select, buttons, etc.) and fixed some future bugs (for example if settings were added in the future, they would have been undefined instead of being assigned the default value)

**Comment by danimateo** [comment]
Added option to choose interval and pause (on and off), noticed that everything looks super clear after staring at this for a while, so some people might like it. Also fixed an issue with multihead (caused by me). 

image

**Comment by danimateo** [comment]
Also added a slider for changing speed, I converted the gif assets to css sprites, so animation can be controlled using css, which allows for better control and less dependencies. I left the old ones in for now anyway.

**Comment by danimateo** [comment]
Added a play/pause button as well, attached image
image

**Comment by belvederef** [comment]
Amazing work @danimateo, I will review and make a new release ASAP. As feedback and in case you want to continue contributing, please open separate PR for different features, it makes it much easier to track development, to review, and to perform a rollback in case any problem arises. Again, thanks for the great work!

**Comment by danimateo** [comment]
@belvederef Yes I wanted to open different PR's, but I was too far gone already, with the refactoring and everything they would have had to have the same base, otherwise it would have been more complicated to merge. Also I didn't think I'll end up doubling the project with this PR at first :)) If there are some features you don't consider ready, I'll separate them in different PR's.

**Comment by danimateo** [comment]
> Also added switch to toggle if the menu should show up the next time the app is started (can be opened by hotkey if no). I think it's useful if you want to run at startup and not see the menu every time. One issue could be if somebody forgets the keybind? They can reinstall perhaps, not a big deal.
> 

Also the issue I was talking about here in case they forget the keybind, opening the application again will open the previously opened menu with 2627e40

**Pull request merged**
